application: twcltestck
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /static/(.*\.css)$
  static_files: static/\1
  upload: static/.*\.css$
  mime_type: "text/css"
- url: /static/(.*\.js)$
  static_files: static/\1
  upload: static/.*\.js$
  mime_type: "application/javascript"
- url: /static/(.*\.gif)$
  static_files: static/\1
  upload: static/.*\.gif$
  mime_type: "image/gif"
- url: /static/(.*\.png)$
  static_files: static/\1
  upload: static/.*\.png$
  mime_type: "image/png"
- url: /static/(.*\.jpg)$
  static_files: static/\1
  upload: static/.*\.jpg$
  mime_type: "image/jpeg"

- url: /.*
  script: main.app

