application: twclck
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static/(.*\.css)$
  static_files: static/\1
  upload: static/.*\.css$
  mime_type: "text/css"
- url: /static/(.*\.js)$
  static_files: static/js/\1
  upload: static/js/.*\.js$
  mime_type: "application/javascript"
- url: /img/(.*\.gif)$
  static_files: img/\1
  upload: img/.*\.gif$
  mime_type: "image/gif"
- url: /img/(.*\.png)$
  static_files: img/\1
  upload: img/.*\.png$
  mime_type: "image/x-png"
- url: /img/(.*\.jpg)$
  static_files: img/\1
  upload: img/.*\.jpg$
  mime_type: "image/jpeg"

- url: /.*
  script: main.app

